### ISSUE TITLE
Visibility of the .csirc example file

### ISSUE THREAD

**Issue by Blizarre** [wasamasa/readline#4]
Hi,

As a new chicken user, I wanted to use the breadline library to improve the experience with `csi` as recommanded in the User manual, but at first glance I could not find anything in the breadline wiki page about it. 

It is only after setting up my second or third environment that I looked again, and realized that I overlooked a link to the "example" directory in the repo, and that it contained a `.csirc`.

I would suggest that the REPL should have a dedicated section in the wiki page, like `Use breadline with csi`, and a direct link to the `.csirc` file in the repository. 

Thank you very much for the bindings!

**Comment by wasamasa** [comment]
Personally, I find the sentence in the Examples section clear enough:

> Further examples for usage in csi and writing your own completer can be found in the repository.

What I could do is adding one more sentence to the Introduction section because it already suggests that breadline can be used for augmenting csi, but doesn't say how. Putting a link there or pointing towards the examples would help.

**Comment by wasamasa** [comment]
I've now put the same link there and mentioned `.csirc`.
